# Generated by Django 4.0.1 on 2022-01-21 08:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0004_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 8, 30, 17, 830156, tzinfo=utc)),
        ),
    ]
