# Generated by Django 4.0.1 on 2022-01-21 18:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0009_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Student'), (2, 'Instructor')], default=0),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 18, 32, 58, 584869, tzinfo=utc)),
        ),
    ]
