# Generated by Django 4.0.1 on 2022-01-22 00:14

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0010_useraccount_role_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=1000)),
                ('duration', models.PositiveSmallIntegerField(default=6)),
                ('thumbnail_image_path', models.ImageField(null=True, upload_to='thumbnail')),
            ],
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2022, 1, 22, 0, 14, 5, 805840, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=1000)),
                ('video', models.FileField(default=None, null=True, upload_to='Lessons', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('material', models.FileField(null=True, upload_to='Material', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'png', 'docx', 'txt'])])),
                ('course', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ocw.courses')),
            ],
        ),
    ]
