# Generated by Django 4.0.1 on 2022-01-22 00:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0011_courses_alter_useraccount_date_joined_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='thumbnail_image_path',
        ),
        migrations.AddField(
            model_name='courses',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='courses',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnail'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='instructor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2022, 1, 22, 0, 52, 4, 614662, tzinfo=utc)),
        ),
    ]
