# Generated by Django 4.0.1 on 2022-01-22 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0021_alter_comments_lesson'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
