# Generated by Django 4.0.1 on 2022-01-22 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0028_remove_lesson_sn'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='sn',
            field=models.IntegerField(default=None),
        ),
    ]
