# Generated by Django 4.0.1 on 2022-01-22 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0029_lesson_sn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='sn',
        ),
    ]
