# Generated by Django 4.0.1 on 2022-02-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0032_alter_courses_instructor_alter_lesson_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='course',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='instructor',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
