# Generated by Django 4.0.1 on 2022-02-09 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0033_remove_enrollment_course_remove_enrollment_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='role',
        ),
    ]
