# Generated by Django 4.0.1 on 2022-02-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0034_remove_useraccount_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='BachelorSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.PositiveSmallIntegerField(default=None)),
                ('external_marks', models.PositiveSmallIntegerField(default=80)),
                ('internal_marks', models.PositiveSmallIntegerField(default=20)),
                ('practical_marks', models.PositiveSmallIntegerField(default=None)),
                ('elective', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('code', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MasterSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.PositiveSmallIntegerField(default=None)),
                ('internal', models.PositiveSmallIntegerField(default=80)),
                ('external', models.PositiveSmallIntegerField(default=20)),
                ('practical_marks', models.PositiveSmallIntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('code', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(default=None, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=100)),
                ('elective', models.BooleanField(default=False)),
                ('implemented_on', models.DateField()),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ocw.department')),
            ],
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.AddField(
            model_name='mastersubject',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ocw.subject'),
        ),
        migrations.AddField(
            model_name='department',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ocw.program'),
        ),
        migrations.AddField(
            model_name='bachelorsubject',
            name='subject',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ocw.subject'),
        ),
    ]
