# Generated by Django 4.0.1 on 2022-02-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0036_subject_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='syllabus',
            field=models.FileField(blank=True, upload_to='syllabus'),
        ),
    ]
