# Generated by Django 4.0.1 on 2022-02-09 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0037_subject_syllabus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(default=None)),
                ('part', models.PositiveSmallIntegerField(default=None)),
                ('department', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ocw.department')),
            ],
        ),
    ]
