# Generated by Django 4.0.1 on 2022-02-10 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0038_semester'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraccount',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='isInstructor',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='is_instructor',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='last_name',
        ),
    ]
