# Generated by Django 4.0.1 on 2022-02-10 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0039_rename_first_name_useraccount_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='syllabus',
        ),
        migrations.AddField(
            model_name='bachelorsubject',
            name='syllabus',
            field=models.FileField(blank=True, upload_to='syllabus'),
        ),
        migrations.AddField(
            model_name='mastersubject',
            name='syllabus',
            field=models.FileField(blank=True, upload_to='syllabus'),
        ),
    ]
