# Generated by Django 4.0.1 on 2022-01-21 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0003_alter_useraccount_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2022, 1, 21, 7, 38, 29, 863204, tzinfo=utc)),
        ),
    ]
