# Generated by Django 4.0.1 on 2022-01-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocw', '0017_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='instructor',
        ),
    ]
