# Generated by Django 4.0.2 on 2022-02-13 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SE', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bachelorsubject',
            name='subt_code',
        ),
        migrations.RemoveField(
            model_name='department',
            name='prog_code',
        ),
        migrations.RemoveField(
            model_name='mastersubject',
            name='practical_marks',
        ),
        migrations.RemoveField(
            model_name='mastersubject',
            name='subt_code',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='dept_code',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='dept_code',
        ),
        migrations.AddField(
            model_name='bachelorsubject',
            name='sub_code',
            field=models.ForeignKey(db_column='sub_code', default=None, on_delete=django.db.models.deletion.CASCADE, to='SE.subject'),
        ),
        migrations.AddField(
            model_name='mastersubject',
            name='sub_code',
            field=models.ForeignKey(db_column='sub_code', default=None, on_delete=django.db.models.deletion.CASCADE, to='SE.subject'),
        ),
        migrations.AddField(
            model_name='program',
            name='dept_code',
            field=models.ForeignKey(db_column='dept_code', default=None, on_delete=django.db.models.deletion.CASCADE, to='SE.department'),
        ),
        migrations.AddField(
            model_name='semester',
            name='prog_code',
            field=models.ForeignKey(db_column='prog_code', default=None, on_delete=django.db.models.deletion.CASCADE, to='SE.program'),
        ),
        migrations.AddField(
            model_name='semester',
            name='sub_code',
            field=models.ForeignKey(db_column='sub_code', default=None, on_delete=django.db.models.deletion.CASCADE, to='SE.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='prog_code',
            field=models.ForeignKey(db_column='prog_code', default=None, on_delete=django.db.models.deletion.CASCADE, to='SE.program'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_code',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='mastersubject',
            name='credit',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='mastersubject',
            name='external',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AlterField(
            model_name='mastersubject',
            name='internal',
            field=models.PositiveSmallIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='prog_code',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='program',
            name='prog_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sub_code',
            field=models.CharField(default=None, max_length=100, primary_key=True, serialize=False),
        ),
    ]
